name: Update Financial Data

on:
  schedule:
    - cron: '0 */6 * * *' # Запуск кожні 6 годин
  workflow_dispatch: # Дозволяє запускати вручну кнопкою

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Перевірка репозиторію
        uses: actions/checkout@v3

      - name: Налаштування Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl

      - name: Запуск скрипта оновлення
        run: python update.py

      - name: Збереження змін на GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json debug_log.txt
          git commit -m "Автоматичне оновлення даних таблиць та логів" || exit 0
          git push
