name: Update Financial Data

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Обов'язково для push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run update script
        run: python update.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Додаємо обидва файли
          git add data.json debug_log.txt
          
          # Якщо змін немає, git commit впаде, тому додаємо || exit 0
          git commit -m "Оновлено дані через Actions" || echo "Змін немає"
          
          git push
